/* Generated by Yosys 0.61+56 (git sha1 a6fc69552, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "hex_7seg_decoder.v:2.1-37.10" *)
module hex_7seg_decoder(in, o_a, o_b, o_c, o_d, o_e, o_f, o_g);
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  input [3:0] in;
  wire [3:0] in;
  (* src = "hex_7seg_decoder.v:4.8-4.11" *)
  output o_a;
  wire o_a;
  (* src = "hex_7seg_decoder.v:5.8-5.11" *)
  output o_b;
  wire o_b;
  (* src = "hex_7seg_decoder.v:6.8-6.11" *)
  output o_c;
  wire o_c;
  (* src = "hex_7seg_decoder.v:7.8-7.11" *)
  output o_d;
  wire o_d;
  (* src = "hex_7seg_decoder.v:8.8-8.11" *)
  output o_e;
  wire o_e;
  (* src = "hex_7seg_decoder.v:9.8-9.11" *)
  output o_f;
  wire o_f;
  (* src = "hex_7seg_decoder.v:10.8-10.11" *)
  output o_g;
  wire o_g;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  wire _25_;
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  wire _26_;
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  wire _27_;
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  (* src = "hex_7seg_decoder.v:4.8-4.11" *)
  wire _53_;
  (* src = "hex_7seg_decoder.v:5.8-5.11" *)
  wire _54_;
  (* src = "hex_7seg_decoder.v:6.8-6.11" *)
  wire _55_;
  (* src = "hex_7seg_decoder.v:7.8-7.11" *)
  wire _56_;
  (* src = "hex_7seg_decoder.v:8.8-8.11" *)
  wire _57_;
  (* src = "hex_7seg_decoder.v:9.8-9.11" *)
  wire _58_;
  (* src = "hex_7seg_decoder.v:10.8-10.11" *)
  wire _59_;
  (* src = "hex_7seg_decoder.v:12.5-12.6" *)
  wire a;
  (* src = "hex_7seg_decoder.v:12.7-12.8" *)
  wire b;
  (* src = "hex_7seg_decoder.v:12.9-12.10" *)
  wire c;
  (* src = "hex_7seg_decoder.v:12.11-12.12" *)
  wire d;
  (* src = "hex_7seg_decoder.v:12.13-12.14" *)
  wire e;
  (* src = "hex_7seg_decoder.v:12.15-12.16" *)
  wire f;
  (* src = "hex_7seg_decoder.v:12.17-12.18" *)
  wire g;
  INV_X1 _60_ (
    .A(_27_),
    .ZN(_29_)
  );
  INV_X1 _61_ (
    .A(_25_),
    .ZN(_30_)
  );
  INV_X1 _62_ (
    .A(_28_),
    .ZN(_31_)
  );
  NOR2_X1 _63_ (
    .A1(_29_),
    .A2(_26_),
    .ZN(_32_)
  );
  NOR3_X1 _64_ (
    .A1(_29_),
    .A2(_26_),
    .A3(_31_),
    .ZN(_33_)
  );
  NAND2_X1 _65_ (
    .A1(_26_),
    .A2(_25_),
    .ZN(_34_)
  );
  NAND2_X1 _66_ (
    .A1(_27_),
    .A2(_34_),
    .ZN(_35_)
  );
  NAND2_X1 _67_ (
    .A1(_29_),
    .A2(_26_),
    .ZN(_36_)
  );
  AOI21_X1 _68_ (
    .A(_28_),
    .B1(_26_),
    .B2(_29_),
    .ZN(_37_)
  );
  AOI22_X1 _69_ (
    .A1(_30_),
    .A2(_33_),
    .B1(_35_),
    .B2(_37_),
    .ZN(_59_)
  );
  NAND2_X1 _70_ (
    .A1(_25_),
    .A2(_33_),
    .ZN(_38_)
  );
  NOR2_X1 _71_ (
    .A1(_26_),
    .A2(_25_),
    .ZN(_39_)
  );
  NOR2_X1 _72_ (
    .A1(_28_),
    .A2(_39_),
    .ZN(_40_)
  );
  AOI22_X1 _73_ (
    .A1(_25_),
    .A2(_33_),
    .B1(_35_),
    .B2(_40_),
    .ZN(_58_)
  );
  OAI21_X1 _74_ (
    .A(_28_),
    .B1(_26_),
    .B2(_27_),
    .ZN(_41_)
  );
  OAI21_X1 _75_ (
    .A(_41_),
    .B1(_32_),
    .B2(_25_),
    .ZN(_57_)
  );
  OAI22_X1 _76_ (
    .A1(_29_),
    .A2(_34_),
    .B1(_36_),
    .B2(_25_),
    .ZN(_42_)
  );
  OR2_X1 _77_ (
    .A1(_26_),
    .A2(_30_),
    .ZN(_43_)
  );
  AOI21_X1 _78_ (
    .A(_28_),
    .B1(_43_),
    .B2(_29_),
    .ZN(_44_)
  );
  OAI21_X1 _79_ (
    .A(_27_),
    .B1(_26_),
    .B2(_25_),
    .ZN(_45_)
  );
  OR2_X1 _80_ (
    .A1(_35_),
    .A2(_39_),
    .ZN(_46_)
  );
  AOI22_X1 _81_ (
    .A1(_28_),
    .A2(_42_),
    .B1(_44_),
    .B2(_46_),
    .ZN(_56_)
  );
  OAI21_X1 _82_ (
    .A(_31_),
    .B1(_36_),
    .B2(_25_),
    .ZN(_47_)
  );
  AND2_X1 _83_ (
    .A1(_27_),
    .A2(_43_),
    .ZN(_48_)
  );
  OAI21_X1 _84_ (
    .A(_47_),
    .B1(_48_),
    .B2(_31_),
    .ZN(_55_)
  );
  OAI21_X1 _85_ (
    .A(_31_),
    .B1(_35_),
    .B2(_39_),
    .ZN(_49_)
  );
  AOI21_X1 _86_ (
    .A(_27_),
    .B1(_26_),
    .B2(_25_),
    .ZN(_50_)
  );
  NAND2_X1 _87_ (
    .A1(_28_),
    .A2(_50_),
    .ZN(_51_)
  );
  NAND3_X1 _88_ (
    .A1(_38_),
    .A2(_49_),
    .A3(_51_),
    .ZN(_54_)
  );
  AOI211_X1 _89_ (
    .A(_31_),
    .B(_50_),
    .C1(_43_),
    .C2(_27_),
    .ZN(_52_)
  );
  AOI21_X1 _90_ (
    .A(_52_),
    .B1(_45_),
    .B2(_44_),
    .ZN(_53_)
  );
  assign a = o_a;
  assign b = o_b;
  assign c = o_c;
  assign d = o_d;
  assign e = o_e;
  assign f = o_f;
  assign g = o_g;
  assign _27_ = in[2];
  assign _26_ = in[1];
  assign _25_ = in[0];
  assign _28_ = in[3];
  assign o_g = _59_;
  assign o_f = _58_;
  assign o_e = _57_;
  assign o_d = _56_;
  assign o_c = _55_;
  assign o_b = _54_;
  assign o_a = _53_;
endmodule
