/* Generated by Yosys 0.61+56 (git sha1 a6fc69552, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* src = "hamming_74_dec.v:1.1-47.10" *)
module hamming_74_dec(i_data, i_parity, o_syndrome, o_data, o_1bit_error, o_2bit_error, o_parity_error);
  (* src = "hamming_74_dec.v:2.12-2.18" *)
  input [6:0] i_data;
  wire [6:0] i_data;
  (* src = "hamming_74_dec.v:3.7-3.15" *)
  input i_parity;
  wire i_parity;
  (* src = "hamming_74_dec.v:4.13-4.23" *)
  output [6:0] o_syndrome;
  wire [6:0] o_syndrome;
  (* src = "hamming_74_dec.v:5.13-5.19" *)
  output [3:0] o_data;
  wire [3:0] o_data;
  (* src = "hamming_74_dec.v:6.8-6.20" *)
  output o_1bit_error;
  wire o_1bit_error;
  (* src = "hamming_74_dec.v:7.8-7.20" *)
  output o_2bit_error;
  wire o_2bit_error;
  (* src = "hamming_74_dec.v:8.8-8.22" *)
  output o_parity_error;
  wire o_parity_error;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  (* src = "hamming_74_dec.v:2.12-2.18" *)
  wire _034_;
  (* src = "hamming_74_dec.v:2.12-2.18" *)
  wire _035_;
  (* src = "hamming_74_dec.v:2.12-2.18" *)
  wire _036_;
  (* src = "hamming_74_dec.v:2.12-2.18" *)
  wire _037_;
  (* src = "hamming_74_dec.v:2.12-2.18" *)
  wire _038_;
  (* src = "hamming_74_dec.v:2.12-2.18" *)
  wire _039_;
  (* src = "hamming_74_dec.v:2.12-2.18" *)
  wire _040_;
  (* src = "hamming_74_dec.v:3.7-3.15" *)
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  (* src = "hamming_74_dec.v:6.8-6.20" *)
  wire _065_;
  (* src = "hamming_74_dec.v:7.8-7.20" *)
  wire _066_;
  (* src = "hamming_74_dec.v:5.13-5.19" *)
  wire _067_;
  (* src = "hamming_74_dec.v:5.13-5.19" *)
  wire _068_;
  (* src = "hamming_74_dec.v:5.13-5.19" *)
  wire _069_;
  (* src = "hamming_74_dec.v:5.13-5.19" *)
  wire _070_;
  (* src = "hamming_74_dec.v:8.8-8.22" *)
  wire _071_;
  (* src = "hamming_74_dec.v:4.13-4.23" *)
  wire _072_;
  (* src = "hamming_74_dec.v:4.13-4.23" *)
  wire _073_;
  (* src = "hamming_74_dec.v:4.13-4.23" *)
  wire _074_;
  (* src = "hamming_74_dec.v:4.13-4.23" *)
  wire _075_;
  (* src = "hamming_74_dec.v:4.13-4.23" *)
  wire _076_;
  (* src = "hamming_74_dec.v:4.13-4.23" *)
  wire _077_;
  (* src = "hamming_74_dec.v:4.13-4.23" *)
  wire _078_;
  (* src = "hamming_74_dec.v:13.11-13.23" *)
  (* unused_bits = "0 1 3" *)
  wire [6:0] data_decoded;
  (* src = "hamming_74_dec.v:12.10-12.18" *)
  wire [6:0] syndrome;
  sky130_fd_sc_hd__xor2_1 _079_ (
    .A(_040_),
    .B(_037_),
    .X(_050_)
  );
  sky130_fd_sc_hd__xnor2_1 _080_ (
    .A(_049_),
    .B(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__xor2_1 _081_ (
    .A(_049_),
    .B(_050_),
    .X(_052_)
  );
  sky130_fd_sc_hd__nand3_1 _082_ (
    .A(_045_),
    .B(_048_),
    .C(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__clkinv_1 _083_ (
    .A(_053_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__xnor2_1 _084_ (
    .A(_036_),
    .B(_053_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand2_1 _085_ (
    .A(_045_),
    .B(_047_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand3_1 _086_ (
    .A(_045_),
    .B(_047_),
    .C(_051_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__clkinv_1 _087_ (
    .A(_055_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__xnor2_1 _088_ (
    .A(_038_),
    .B(_055_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _089_ (
    .A(_045_),
    .SLEEP(_047_),
    .X(_056_)
  );
  sky130_fd_sc_hd__or3_1 _090_ (
    .A(_045_),
    .B(_047_),
    .C(_052_),
    .X(_057_)
  );
  sky130_fd_sc_hd__clkinv_1 _091_ (
    .A(_057_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__xnor2_1 _092_ (
    .A(_039_),
    .B(_057_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand3_1 _093_ (
    .A(_045_),
    .B(_048_),
    .C(_051_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__clkinv_1 _094_ (
    .A(_058_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__xnor2_1 _095_ (
    .A(_040_),
    .B(_058_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor3_1 _096_ (
    .A(_045_),
    .B(_048_),
    .C(_051_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__xnor2_1 _097_ (
    .A(_040_),
    .B(_041_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__xnor2_1 _098_ (
    .A(_049_),
    .B(_060_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__xor2_1 _099_ (
    .A(_035_),
    .B(_037_),
    .X(_062_)
  );
  sky130_fd_sc_hd__xnor2_1 _100_ (
    .A(_044_),
    .B(_062_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__xnor2_1 _101_ (
    .A(_061_),
    .B(_063_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor2_1 _102_ (
    .A(_059_),
    .B(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nor2b_1 _103_ (
    .A(_059_),
    .B_N(_064_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _104_ (
    .A(_059_),
    .SLEEP(_064_),
    .X(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _105_ (
    .A(_051_),
    .B(_054_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nor2_1 _106_ (
    .A(_051_),
    .B(_056_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor3_1 _107_ (
    .A(_045_),
    .B(_048_),
    .C(_052_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__xnor2_1 _108_ (
    .A(_040_),
    .B(_036_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__xor2_1 _109_ (
    .A(_034_),
    .B(_038_),
    .X(_043_)
  );
  sky130_fd_sc_hd__xor2_1 _110_ (
    .A(_036_),
    .B(_034_),
    .X(_044_)
  );
  sky130_fd_sc_hd__xnor2_1 _111_ (
    .A(_042_),
    .B(_043_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__xor2_1 _112_ (
    .A(_035_),
    .B(_039_),
    .X(_046_)
  );
  sky130_fd_sc_hd__xor2_1 _113_ (
    .A(_042_),
    .B(_046_),
    .X(_047_)
  );
  sky130_fd_sc_hd__xnor2_1 _114_ (
    .A(_042_),
    .B(_046_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__xnor2_1 _115_ (
    .A(_038_),
    .B(_039_),
    .Y(_049_)
  );
  assign { data_decoded[6:4], data_decoded[2] } = o_data;
  assign syndrome = o_syndrome;
  assign _040_ = i_data[6];
  assign _036_ = i_data[2];
  assign _034_ = i_data[0];
  assign _038_ = i_data[4];
  assign _035_ = i_data[1];
  assign _039_ = i_data[5];
  assign _037_ = i_data[3];
  assign o_syndrome[2] = _074_;
  assign o_data[0] = _067_;
  assign o_syndrome[4] = _076_;
  assign o_data[1] = _068_;
  assign o_syndrome[5] = _077_;
  assign o_data[2] = _069_;
  assign o_syndrome[6] = _078_;
  assign o_data[3] = _070_;
  assign _041_ = i_parity;
  assign o_1bit_error = _065_;
  assign o_2bit_error = _066_;
  assign o_parity_error = _071_;
  assign o_syndrome[0] = _072_;
  assign o_syndrome[1] = _073_;
  assign o_syndrome[3] = _075_;
endmodule

(* src = "hamming_74_enco.v:1.1-15.10" *)
module hamming_74_enco(i_data, o_hamming_code, o_parity);
  (* src = "hamming_74_enco.v:2.12-2.18" *)
  input [3:0] i_data;
  wire [3:0] i_data;
  (* src = "hamming_74_enco.v:3.14-3.28" *)
  output [6:0] o_hamming_code;
  wire [6:0] o_hamming_code;
  (* src = "hamming_74_enco.v:4.8-4.16" *)
  output o_parity;
  wire o_parity;
  (* src = "hamming_74_enco.v:2.12-2.18" *)
  wire _00_;
  (* src = "hamming_74_enco.v:2.12-2.18" *)
  wire _01_;
  (* src = "hamming_74_enco.v:2.12-2.18" *)
  wire _02_;
  (* src = "hamming_74_enco.v:2.12-2.18" *)
  wire _03_;
  (* src = "hamming_74_enco.v:4.8-4.16" *)
  wire _04_;
  (* src = "hamming_74_enco.v:5.11-5.13" *)
  wire _05_;
  (* src = "hamming_74_enco.v:5.8-5.10" *)
  wire _06_;
  (* src = "hamming_74_enco.v:5.5-5.7" *)
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "hamming_74_enco.v:5.11-5.13" *)
  wire p1;
  (* src = "hamming_74_enco.v:5.8-5.10" *)
  wire p2;
  (* src = "hamming_74_enco.v:5.5-5.7" *)
  wire p4;
  sky130_fd_sc_hd__xor3_1 _16_ (
    .A(_03_),
    .B(_01_),
    .C(_00_),
    .X(_05_)
  );
  sky130_fd_sc_hd__xor3_1 _17_ (
    .A(_03_),
    .B(_00_),
    .C(_02_),
    .X(_06_)
  );
  sky130_fd_sc_hd__xor3_1 _18_ (
    .A(_03_),
    .B(_01_),
    .C(_02_),
    .X(_07_)
  );
  sky130_fd_sc_hd__xor3_1 _19_ (
    .A(_01_),
    .B(_00_),
    .C(_02_),
    .X(_04_)
  );
  assign o_hamming_code = { i_data[3:1], p4, i_data[0], p2, p1 };
  assign _03_ = i_data[3];
  assign _01_ = i_data[1];
  assign _00_ = i_data[0];
  assign p1 = _05_;
  assign _02_ = i_data[2];
  assign p2 = _06_;
  assign p4 = _07_;
  assign o_parity = _04_;
endmodule

(* top =  1  *)
(* src = "hamming_secded_top.v:1.1-60.10" *)
module hamming_secded_top(i_secded, i_noise, o_7seg, o_secded, o_1bit_error, o_2bit_error, o_parity_error);
  (* src = "hamming_secded_top.v:2.16-2.24" *)
  input [3:0] i_secded;
  wire [3:0] i_secded;
  (* src = "hamming_secded_top.v:3.16-3.23" *)
  input [4:0] i_noise;
  wire [4:0] i_noise;
  (* src = "hamming_secded_top.v:4.17-4.23" *)
  output [6:0] o_7seg;
  wire [6:0] o_7seg;
  (* src = "hamming_secded_top.v:5.18-5.26" *)
  output [3:0] o_secded;
  wire [3:0] o_secded;
  (* src = "hamming_secded_top.v:6.13-6.25" *)
  output o_1bit_error;
  wire o_1bit_error;
  (* src = "hamming_secded_top.v:7.12-7.24" *)
  output o_2bit_error;
  wire o_2bit_error;
  (* src = "hamming_secded_top.v:8.12-8.26" *)
  output o_parity_error;
  wire o_parity_error;
  (* src = "hamming_secded_top.v:11.11-11.27" *)
  wire [6:0] enc_hamming_code;
  (* src = "hamming_secded_top.v:12.6-12.16" *)
  wire enc_parity;
  (* src = "hamming_secded_top.v:18.11-18.18" *)
  wire [2:0] in_7seg;
  (* src = "hamming_secded_top.v:14.12-14.32" *)
  wire [6:0] o_noise_hamming_code;
  (* src = "hamming_secded_top.v:15.9-15.23" *)
  wire o_noise_parity;
  (* src = "hamming_secded_top.v:17.12-17.22" *)
  wire [6:0] o_syndrome;
  (* module_not_derived = 32'd1 *)
  (* src = "hamming_secded_top.v:21.19-21.96" *)
  hamming_74_enco m1 (
    .i_data(i_secded),
    .o_hamming_code(enc_hamming_code),
    .o_parity(enc_parity)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "hamming_secded_top.v:24.15-26.49" *)
  noise_adder m2 (
    .i_data({ enc_parity, enc_hamming_code }),
    .i_noise(i_noise),
    .o_data({ o_noise_parity, o_noise_hamming_code })
  );
  (* module_not_derived = 32'd1 *)
  (* src = "hamming_secded_top.v:30.17-38.3" *)
  hamming_74_dec m3 (
    .i_data(o_noise_hamming_code),
    .i_parity(o_noise_parity),
    .o_1bit_error(o_1bit_error),
    .o_2bit_error(o_2bit_error),
    .o_data(o_secded),
    .o_parity_error(o_parity_error),
    .o_syndrome(o_syndrome)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "hamming_secded_top.v:41.19-45.2" *)
  priority_encoder m4 (
    .d({ 1'h0, o_syndrome }),
    .q(in_7seg)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "hamming_secded_top.v:48.18-58.2" *)
  hex_7seg_decoder m5 (
    .in({ 1'h0, in_7seg }),
    .o_a(o_7seg[0]),
    .o_b(o_7seg[1]),
    .o_c(o_7seg[2]),
    .o_d(o_7seg[3]),
    .o_e(o_7seg[4]),
    .o_f(o_7seg[5]),
    .o_g(o_7seg[6])
  );
endmodule

(* src = "hex_7seg_decoder.v:2.1-37.10" *)
module hex_7seg_decoder(in, o_a, o_b, o_c, o_d, o_e, o_f, o_g);
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  input [3:0] in;
  wire [3:0] in;
  (* src = "hex_7seg_decoder.v:4.8-4.11" *)
  output o_a;
  wire o_a;
  (* src = "hex_7seg_decoder.v:5.8-5.11" *)
  output o_b;
  wire o_b;
  (* src = "hex_7seg_decoder.v:6.8-6.11" *)
  output o_c;
  wire o_c;
  (* src = "hex_7seg_decoder.v:7.8-7.11" *)
  output o_d;
  wire o_d;
  (* src = "hex_7seg_decoder.v:8.8-8.11" *)
  output o_e;
  wire o_e;
  (* src = "hex_7seg_decoder.v:9.8-9.11" *)
  output o_f;
  wire o_f;
  (* src = "hex_7seg_decoder.v:10.8-10.11" *)
  output o_g;
  wire o_g;
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  wire _00_;
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  wire _01_;
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  wire _02_;
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  (* src = "hex_7seg_decoder.v:4.8-4.11" *)
  wire _24_;
  (* src = "hex_7seg_decoder.v:5.8-5.11" *)
  wire _25_;
  (* src = "hex_7seg_decoder.v:6.8-6.11" *)
  wire _26_;
  (* src = "hex_7seg_decoder.v:7.8-7.11" *)
  wire _27_;
  (* src = "hex_7seg_decoder.v:8.8-8.11" *)
  wire _28_;
  (* src = "hex_7seg_decoder.v:9.8-9.11" *)
  wire _29_;
  (* src = "hex_7seg_decoder.v:10.8-10.11" *)
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  (* src = "hex_7seg_decoder.v:12.5-12.6" *)
  wire a;
  (* src = "hex_7seg_decoder.v:12.7-12.8" *)
  wire b;
  (* src = "hex_7seg_decoder.v:12.9-12.10" *)
  wire c;
  (* src = "hex_7seg_decoder.v:12.11-12.12" *)
  wire d;
  (* src = "hex_7seg_decoder.v:12.13-12.14" *)
  wire e;
  (* src = "hex_7seg_decoder.v:12.15-12.16" *)
  wire f;
  (* src = "hex_7seg_decoder.v:12.17-12.18" *)
  wire g;
  sky130_fd_sc_hd__clkinv_1 _56_ (
    .A(_02_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _57_ (
    .A(_02_),
    .SLEEP(_01_),
    .X(_05_)
  );
  sky130_fd_sc_hd__nand2_1 _58_ (
    .A(_03_),
    .B(_05_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__a21boi_0 _59_ (
    .A1(_01_),
    .A2(_00_),
    .B1_N(_02_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__and3_1 _60_ (
    .A(_02_),
    .B(_01_),
    .C(_00_),
    .X(_08_)
  );
  sky130_fd_sc_hd__nor2_1 _61_ (
    .A(_02_),
    .B(_01_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor2_1 _62_ (
    .A(_08_),
    .B(_09_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__o22a_1 _63_ (
    .A1(_00_),
    .A2(_06_),
    .B1(_10_),
    .B2(_03_),
    .X(_30_)
  );
  sky130_fd_sc_hd__nand3_1 _64_ (
    .A(_00_),
    .B(_03_),
    .C(_05_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor2_1 _65_ (
    .A(_01_),
    .B(_00_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__o31a_1 _66_ (
    .A1(_03_),
    .A2(_07_),
    .A3(_12_),
    .B1(_11_),
    .X(_29_)
  );
  sky130_fd_sc_hd__o21ai_0 _67_ (
    .A1(_02_),
    .A2(_01_),
    .B1(_03_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o21ai_0 _68_ (
    .A1(_00_),
    .A2(_05_),
    .B1(_13_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__nor3b_1 _69_ (
    .A(_02_),
    .B(_00_),
    .C_N(_01_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__o21ai_0 _70_ (
    .A1(_08_),
    .A2(_14_),
    .B1(_03_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand2b_1 _71_ (
    .A_N(_01_),
    .B(_00_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__a21oi_1 _72_ (
    .A1(_04_),
    .A2(_16_),
    .B1(_03_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__o21ai_0 _73_ (
    .A1(_01_),
    .A2(_00_),
    .B1(_02_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__a21oi_1 _74_ (
    .A1(_01_),
    .A2(_00_),
    .B1(_18_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__o21ai_0 _75_ (
    .A1(_01_),
    .A2(_00_),
    .B1(_07_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a21boi_0 _76_ (
    .A1(_17_),
    .A2(_20_),
    .B1_N(_15_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__a21bo_1 _77_ (
    .A1(_02_),
    .A2(_16_),
    .B1_N(_03_),
    .X(_21_)
  );
  sky130_fd_sc_hd__o21ai_0 _78_ (
    .A1(_03_),
    .A2(_14_),
    .B1(_21_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__a21oi_1 _79_ (
    .A1(_01_),
    .A2(_00_),
    .B1(_02_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__nand2_1 _80_ (
    .A(_03_),
    .B(_22_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__o211ai_1 _81_ (
    .A1(_03_),
    .A2(_19_),
    .B1(_23_),
    .C1(_11_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _82_ (
    .A1_N(_22_),
    .A2_N(_21_),
    .B1(_18_),
    .B2(_17_),
    .Y(_24_)
  );
  assign a = o_a;
  assign b = o_b;
  assign c = o_c;
  assign d = o_d;
  assign e = o_e;
  assign f = o_f;
  assign g = o_g;
  assign _02_ = in[2];
  assign _01_ = in[1];
  assign _00_ = in[0];
  assign _03_ = in[3];
  assign o_g = _30_;
  assign o_f = _29_;
  assign o_e = _28_;
  assign o_d = _27_;
  assign o_c = _26_;
  assign o_b = _25_;
  assign o_a = _24_;
endmodule

(* src = "noise_adder.v:1.1-22.10" *)
module noise_adder(i_data, i_noise, o_data);
  (* src = "noise_adder.v:2.12-2.18" *)
  input [7:0] i_data;
  wire [7:0] i_data;
  (* src = "noise_adder.v:3.12-3.19" *)
  input [4:0] i_noise;
  wire [4:0] i_noise;
  (* src = "noise_adder.v:4.13-4.19" *)
  output [7:0] o_data;
  wire [7:0] o_data;
  (* src = "noise_adder.v:2.12-2.18" *)
  wire _00_;
  (* src = "noise_adder.v:2.12-2.18" *)
  wire _01_;
  (* src = "noise_adder.v:2.12-2.18" *)
  wire _02_;
  (* src = "noise_adder.v:2.12-2.18" *)
  wire _03_;
  (* src = "noise_adder.v:2.12-2.18" *)
  wire _04_;
  (* src = "noise_adder.v:2.12-2.18" *)
  wire _05_;
  (* src = "noise_adder.v:2.12-2.18" *)
  wire _06_;
  (* src = "noise_adder.v:2.12-2.18" *)
  wire _07_;
  (* src = "noise_adder.v:3.12-3.19" *)
  wire _08_;
  (* src = "noise_adder.v:3.12-3.19" *)
  wire _09_;
  (* src = "noise_adder.v:3.12-3.19" *)
  wire _10_;
  (* src = "noise_adder.v:3.12-3.19" *)
  wire _11_;
  (* src = "noise_adder.v:3.12-3.19" *)
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  (* src = "noise_adder.v:4.13-4.19" *)
  wire _23_;
  (* src = "noise_adder.v:4.13-4.19" *)
  wire _24_;
  (* src = "noise_adder.v:4.13-4.19" *)
  wire _25_;
  (* src = "noise_adder.v:4.13-4.19" *)
  wire _26_;
  (* src = "noise_adder.v:4.13-4.19" *)
  wire _27_;
  (* src = "noise_adder.v:4.13-4.19" *)
  wire _28_;
  (* src = "noise_adder.v:4.13-4.19" *)
  wire _29_;
  (* src = "noise_adder.v:4.13-4.19" *)
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  wire _49_;
  wire _50_;
  wire _51_;
  wire _52_;
  wire _53_;
  wire _54_;
  wire _55_;
  wire _56_;
  wire _57_;
  wire _58_;
  wire _59_;
  wire _60_;
  wire _61_;
  wire _62_;
  wire _63_;
  wire _64_;
  wire _65_;
  wire _66_;
  wire _67_;
  wire _68_;
  wire _69_;
  wire _70_;
  (* src = "noise_adder.v:7.10-7.22" *)
  wire [2:0] error_at_bit;
  sky130_fd_sc_hd__nand2b_1 _71_ (
    .A_N(_09_),
    .B(_08_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand2_1 _72_ (
    .A(_08_),
    .B(_09_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nand4_1 _73_ (
    .A(_10_),
    .B(_08_),
    .C(_09_),
    .D(_11_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__o21ai_0 _74_ (
    .A1(_10_),
    .A2(_13_),
    .B1(_15_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__xor2_1 _75_ (
    .A(_00_),
    .B(_16_),
    .X(_23_)
  );
  sky130_fd_sc_hd__nor3b_1 _76_ (
    .A(_10_),
    .B(_08_),
    .C_N(_09_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__xor2_1 _77_ (
    .A(_01_),
    .B(_17_),
    .X(_24_)
  );
  sky130_fd_sc_hd__nor2_1 _78_ (
    .A(_10_),
    .B(_14_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__xor2_1 _79_ (
    .A(_02_),
    .B(_18_),
    .X(_25_)
  );
  sky130_fd_sc_hd__nor3b_1 _80_ (
    .A(_08_),
    .B(_09_),
    .C_N(_10_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__xor2_1 _81_ (
    .A(_03_),
    .B(_19_),
    .X(_26_)
  );
  sky130_fd_sc_hd__nand3b_1 _82_ (
    .A_N(_09_),
    .B(_08_),
    .C(_10_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__xnor2_1 _83_ (
    .A(_04_),
    .B(_20_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__nand3b_1 _84_ (
    .A_N(_08_),
    .B(_09_),
    .C(_10_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__xnor2_1 _85_ (
    .A(_05_),
    .B(_21_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__a31oi_1 _86_ (
    .A1(_10_),
    .A2(_08_),
    .A3(_09_),
    .B1(_11_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__xnor2_1 _87_ (
    .A(_06_),
    .B(_22_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__xor2_1 _88_ (
    .A(_12_),
    .B(_07_),
    .X(_30_)
  );
  assign error_at_bit = i_noise[2:0];
  assign _10_ = i_noise[2];
  assign _08_ = i_noise[0];
  assign _09_ = i_noise[1];
  assign _11_ = i_noise[3];
  assign _00_ = i_data[0];
  assign o_data[0] = _23_;
  assign _01_ = i_data[1];
  assign o_data[1] = _24_;
  assign _02_ = i_data[2];
  assign o_data[2] = _25_;
  assign _03_ = i_data[3];
  assign o_data[3] = _26_;
  assign _04_ = i_data[4];
  assign o_data[4] = _27_;
  assign _05_ = i_data[5];
  assign o_data[5] = _28_;
  assign _06_ = i_data[6];
  assign o_data[6] = _29_;
  assign _12_ = i_noise[4];
  assign _07_ = i_data[7];
  assign o_data[7] = _30_;
endmodule

(* src = "priority_encoder.v:2.1-21.10" *)
module priority_encoder(d, q, v);
  (* src = "priority_encoder.v:3.13-3.14" *)
  input [7:0] d;
  wire [7:0] d;
  (* src = "priority_encoder.v:4.18-4.19" *)
  output [2:0] q;
  wire [2:0] q;
  (* src = "priority_encoder.v:5.13-5.14" *)
  output v;
  wire v;
  (* src = "priority_encoder.v:3.13-3.14" *)
  wire _00_;
  (* src = "priority_encoder.v:3.13-3.14" *)
  wire _01_;
  (* src = "priority_encoder.v:3.13-3.14" *)
  wire _02_;
  (* src = "priority_encoder.v:3.13-3.14" *)
  wire _03_;
  (* src = "priority_encoder.v:3.13-3.14" *)
  wire _04_;
  (* src = "priority_encoder.v:3.13-3.14" *)
  wire _05_;
  (* src = "priority_encoder.v:3.13-3.14" *)
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "priority_encoder.v:4.18-4.19" *)
  wire _14_;
  (* src = "priority_encoder.v:4.18-4.19" *)
  wire _15_;
  (* src = "priority_encoder.v:4.18-4.19" *)
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  sky130_fd_sc_hd__clkinv_1 _28_ (
    .A(_02_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand2b_1 _29_ (
    .A_N(_01_),
    .B(_00_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a21oi_1 _30_ (
    .A1(_07_),
    .A2(_08_),
    .B1(_03_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor2_1 _31_ (
    .A(_04_),
    .B(_09_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__o21bai_1 _32_ (
    .A1(_05_),
    .A2(_10_),
    .B1_N(_06_),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor2_1 _33_ (
    .A(_03_),
    .B(_04_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__o21ai_0 _34_ (
    .A1(_01_),
    .A2(_02_),
    .B1(_11_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nor2_1 _35_ (
    .A(_05_),
    .B(_06_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand2_1 _36_ (
    .A(_12_),
    .B(_13_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nand2_1 _37_ (
    .A(_11_),
    .B(_13_),
    .Y(_16_)
  );
  assign v = 1'h1;
  assign _00_ = d[1];
  assign _01_ = d[2];
  assign _02_ = d[3];
  assign _03_ = d[4];
  assign _04_ = d[5];
  assign _05_ = d[6];
  assign _06_ = d[7];
  assign q[0] = _14_;
  assign q[1] = _15_;
  assign q[2] = _16_;
endmodule
