/* Generated by Yosys 0.61+56 (git sha1 a6fc69552, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "hex_7seg_decoder.v:2.1-37.10" *)
module hex_7seg_decoder(in, o_a, o_b, o_c, o_d, o_e, o_f, o_g);
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  input [3:0] in;
  wire [3:0] in;
  (* src = "hex_7seg_decoder.v:4.8-4.11" *)
  output o_a;
  wire o_a;
  (* src = "hex_7seg_decoder.v:5.8-5.11" *)
  output o_b;
  wire o_b;
  (* src = "hex_7seg_decoder.v:6.8-6.11" *)
  output o_c;
  wire o_c;
  (* src = "hex_7seg_decoder.v:7.8-7.11" *)
  output o_d;
  wire o_d;
  (* src = "hex_7seg_decoder.v:8.8-8.11" *)
  output o_e;
  wire o_e;
  (* src = "hex_7seg_decoder.v:9.8-9.11" *)
  output o_f;
  wire o_f;
  (* src = "hex_7seg_decoder.v:10.8-10.11" *)
  output o_g;
  wire o_g;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  wire _25_;
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  wire _26_;
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  wire _27_;
  (* src = "hex_7seg_decoder.v:3.12-3.14" *)
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  wire _45_;
  wire _46_;
  wire _47_;
  wire _48_;
  (* src = "hex_7seg_decoder.v:4.8-4.11" *)
  wire _49_;
  (* src = "hex_7seg_decoder.v:5.8-5.11" *)
  wire _50_;
  (* src = "hex_7seg_decoder.v:6.8-6.11" *)
  wire _51_;
  (* src = "hex_7seg_decoder.v:7.8-7.11" *)
  wire _52_;
  (* src = "hex_7seg_decoder.v:8.8-8.11" *)
  wire _53_;
  (* src = "hex_7seg_decoder.v:9.8-9.11" *)
  wire _54_;
  (* src = "hex_7seg_decoder.v:10.8-10.11" *)
  wire _55_;
  (* src = "hex_7seg_decoder.v:12.5-12.6" *)
  wire a;
  (* src = "hex_7seg_decoder.v:12.7-12.8" *)
  wire b;
  (* src = "hex_7seg_decoder.v:12.9-12.10" *)
  wire c;
  (* src = "hex_7seg_decoder.v:12.11-12.12" *)
  wire d;
  (* src = "hex_7seg_decoder.v:12.13-12.14" *)
  wire e;
  (* src = "hex_7seg_decoder.v:12.15-12.16" *)
  wire f;
  (* src = "hex_7seg_decoder.v:12.17-12.18" *)
  wire g;
  sky130_fd_sc_hd__clkinv_1 _56_ (
    .A(_27_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _57_ (
    .A(_27_),
    .SLEEP(_26_),
    .X(_30_)
  );
  sky130_fd_sc_hd__nand2_1 _58_ (
    .A(_28_),
    .B(_30_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__a21boi_0 _59_ (
    .A1(_26_),
    .A2(_25_),
    .B1_N(_27_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__and3_1 _60_ (
    .A(_27_),
    .B(_26_),
    .C(_25_),
    .X(_33_)
  );
  sky130_fd_sc_hd__nor2_1 _61_ (
    .A(_27_),
    .B(_26_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__nor2_1 _62_ (
    .A(_33_),
    .B(_34_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__o22a_1 _63_ (
    .A1(_25_),
    .A2(_31_),
    .B1(_35_),
    .B2(_28_),
    .X(_55_)
  );
  sky130_fd_sc_hd__nand3_1 _64_ (
    .A(_25_),
    .B(_28_),
    .C(_30_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__nor2_1 _65_ (
    .A(_26_),
    .B(_25_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__o31a_1 _66_ (
    .A1(_28_),
    .A2(_32_),
    .A3(_37_),
    .B1(_36_),
    .X(_54_)
  );
  sky130_fd_sc_hd__o21ai_0 _67_ (
    .A1(_27_),
    .A2(_26_),
    .B1(_28_),
    .Y(_38_)
  );
  sky130_fd_sc_hd__o21ai_0 _68_ (
    .A1(_25_),
    .A2(_30_),
    .B1(_38_),
    .Y(_53_)
  );
  sky130_fd_sc_hd__nor3b_1 _69_ (
    .A(_27_),
    .B(_25_),
    .C_N(_26_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__o21ai_0 _70_ (
    .A1(_33_),
    .A2(_39_),
    .B1(_28_),
    .Y(_40_)
  );
  sky130_fd_sc_hd__nand2b_1 _71_ (
    .A_N(_26_),
    .B(_25_),
    .Y(_41_)
  );
  sky130_fd_sc_hd__a21oi_1 _72_ (
    .A1(_29_),
    .A2(_41_),
    .B1(_28_),
    .Y(_42_)
  );
  sky130_fd_sc_hd__o21ai_0 _73_ (
    .A1(_26_),
    .A2(_25_),
    .B1(_27_),
    .Y(_43_)
  );
  sky130_fd_sc_hd__a21oi_1 _74_ (
    .A1(_26_),
    .A2(_25_),
    .B1(_43_),
    .Y(_44_)
  );
  sky130_fd_sc_hd__o21ai_0 _75_ (
    .A1(_26_),
    .A2(_25_),
    .B1(_32_),
    .Y(_45_)
  );
  sky130_fd_sc_hd__a21boi_0 _76_ (
    .A1(_42_),
    .A2(_45_),
    .B1_N(_40_),
    .Y(_52_)
  );
  sky130_fd_sc_hd__a21bo_1 _77_ (
    .A1(_27_),
    .A2(_41_),
    .B1_N(_28_),
    .X(_46_)
  );
  sky130_fd_sc_hd__o21ai_0 _78_ (
    .A1(_28_),
    .A2(_39_),
    .B1(_46_),
    .Y(_51_)
  );
  sky130_fd_sc_hd__a21oi_1 _79_ (
    .A1(_26_),
    .A2(_25_),
    .B1(_27_),
    .Y(_47_)
  );
  sky130_fd_sc_hd__nand2_1 _80_ (
    .A(_28_),
    .B(_47_),
    .Y(_48_)
  );
  sky130_fd_sc_hd__o211ai_1 _81_ (
    .A1(_28_),
    .A2(_44_),
    .B1(_48_),
    .C1(_36_),
    .Y(_50_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _82_ (
    .A1_N(_47_),
    .A2_N(_46_),
    .B1(_43_),
    .B2(_42_),
    .Y(_49_)
  );
  assign a = o_a;
  assign b = o_b;
  assign c = o_c;
  assign d = o_d;
  assign e = o_e;
  assign f = o_f;
  assign g = o_g;
  assign _27_ = in[2];
  assign _26_ = in[1];
  assign _25_ = in[0];
  assign _28_ = in[3];
  assign o_g = _55_;
  assign o_f = _54_;
  assign o_e = _53_;
  assign o_d = _52_;
  assign o_c = _51_;
  assign o_b = _50_;
  assign o_a = _49_;
endmodule
